Move away from require with path.resolve().
The jscodeshift used for the transformation:
```
const path = require('path');

export default function transformer(file, api) {
  const j = api.jscodeshift;

  return j(file.source)
    .find(j.CallExpression, {callee: {type: "Identifier", name: "require"}})
    .filter(callExpr => {  // has path.resolve() as an argument
      return callExpr.value.arguments[0].type === "CallExpression" // call expression (not a literal)
        && callExpr.value.arguments[0].callee.property.name === "resolve"
        && callExpr.value.arguments[0].arguments[0].type === "Literal";
    })
    .forEach(callExpr => {
      const originalPath = callExpr.value.arguments[0].arguments[0].value;
      const absolutePath = path.resolve(originalPath);
      const relativePath = path.relative(path.dirname(file.path), absolutePath);

      // files from the same directory resulted in 'Error: Cannot find module' if './' was not added
      callExpr.value.arguments[0] = j.literal(relativePath.startsWith('.') ? relativePath : "./" + relativePath);
    })
    .toSource({quote: 'single'});
}
```