Translations update from Weblate (#1865)
* Translated using Weblate (Ukrainian)

Currently translated at 33.3% (2 of 6 strings)

Translation: Trustroots/search
Translate-URL: https://hosted.weblate.org/projects/trustroots/search/uk/

* Fix test warnings & errors (#1868)

Fixes errors when running Jest:

* Fix deprecated toBeEmpty:

   > Warning: toBeEmpty has been deprecated and will be removed in future updates. Please use instead toBeEmptyDOMElement for finding empty nodes in the DOM.

* Fix "Not implemented: HTMLCanvasElement.prototype.getContext"

    >  Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

* Fix tiny code-readability smell

* Clean-up CSP header from un-used values (#1869)

Removes:
- MailChimp (was for newsletter)
- Uploadcare.com (was for Circle images)
- Maitreapp (was for invite only feature)
- Clean out a couple commented rules

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

* Changed leave a reference to share an experience. (#1867)

* [CI] Extract locales

[ci skip]

* Feedback question changes depending on recommend state (#1861)

* adding gender to references

* refactoring to avoid duplicate code and changing to suggested shorthand

* added different sentences  for feedback question depending on recommend  and report state

* Revert "refactoring to avoid duplicate code and changing to suggested shorthand"

This reverts commit 80a94dd3cfddf657814c152293fcb8bae0b7b273.

* Revert "adding gender to references"

This reverts commit ff3c056aec7ba23ac1d865e11ff15b29443447b1.

* delete word enjoy and removing add gender commits

* delete word enjoy

* [CI] Extract locales

[ci skip]

* Update sentry monorepo to v5.27.6 (#1871)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Translated using Weblate (Spanish)

Currently translated at 100.0% (28 of 28 strings)

Translation: Trustroots/messages
Translate-URL: https://hosted.weblate.org/projects/trustroots/messages/es/

* Translated using Weblate (Spanish)

Currently translated at 7.1% (23 of 321 strings)

Translation: Trustroots/pages
Translate-URL: https://hosted.weblate.org/projects/trustroots/pages/es/

* Update dependency gulp-load-plugins to v2.0.6 (#1870)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Update babel monorepo (#1872)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Update dependency eslint-plugin-jest-dom to v3.3.0 (#1874)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Change "other" to "other gender" (#1866)

"Other gender" instead of "other" so it's clear what we are talking about in UI.

* Update dependency expose-loader to v1.0.3 (#1876)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Update dependency autoprefixer to v10.0.4 (#1873)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* [CI] Extract locales

[ci skip]

* Update dependency ng-annotate-patched to v1.13.0 (#1877)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Update dependency postcss to v8.1.10 (#1879)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* Translated using Weblate (Italian)

Currently translated at 100.0% (41 of 41 strings)

Translation: Trustroots/users
Translate-URL: https://hosted.weblate.org/projects/trustroots/users/it/

* Translated using Weblate (Italian)

Currently translated at 100.0% (321 of 321 strings)

Translation: Trustroots/pages
Translate-URL: https://hosted.weblate.org/projects/trustroots/pages/it/

* Hide "public" title unless also "pending" experiences are showing (#1880)

* Split references section into its own component
* Change copy of pending/public for clarity
* Don't show "public" title unless we show also "pending" title

* [CI] Extract locales

[ci skip]

* Experiences list: improve visuals & copy for pending reference (#1882)

* [CI] Extract locales

[ci skip]

* Translated using Weblate (Spanish)

Currently translated at 8.4% (27 of 321 strings)

Translation: Trustroots/pages
Translate-URL: https://hosted.weblate.org/projects/trustroots/pages/es/

Co-authored-by: Hlib <hlibbabii@gmail.com>
Co-authored-by: Mikael Korpela <mikael@ihminen.org>
Co-authored-by: Salami <68077617+MrSalami@users.noreply.github.com>
Co-authored-by: Travis CI User <travis@example.org>
Co-authored-by: chagai95 <31655082+chagai95@users.noreply.github.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Martin Lobert <loberto@gmail.com>
Co-authored-by: Mauro Piccotti <mauro.piccotti@gmail.com>